### ISSUE TITLE
JSONpedia Live Service not working

### ISSUE THREAD

**Issue by krishh-konar** [dbpedia/tablist-extractor#3]
The legacy system using Jsonpedia live isn't working anymore, missing some key imports from `table-extractor`. Add the required modules/code within the current code. I'm adding the traceback for a quick reference.

```
Traceback (most recent call last):
  File "domainExplorer.py", line 332, in <module>
    start_exploration()
  File "domainExplorer.py", line 32, in start_exploration
    analyze_uri_resource_list(uri_resource_list)
  File "domainExplorer.py", line 54, in analyze_uri_resource_list
    resDict = get_titles_and_list_contents(single_uri)
  File "domainExplorer.py", line 286, in get_titles_and_list_contents
    resDict = explorer_tools.wiki_parser(res_name)
  File "/Users/krishanu.k/Personal_Projects/tablist-extractor/tablist-extractor/domain_explorer/ExplorerTools.py", line 193, in wiki_parser
    resDict = wiki_parser.main_parser()
  File "/Users/krishanu.k/Personal_Projects/tablist-extractor/tablist-extractor/domain_explorer/wikiParser.py", line 57, in main_parser
    result = self.jsonpedia_convert(self.language, self.resource)  # result obtained from JSONpedia in form of a list of sections
  File "/Users/krishanu.k/Personal_Projects/tablist-extractor/tablist-extractor/domain_explorer/wikiParser.py", line 208, in jsonpedia_convert
    sections = utils.json_req(jsonpediaURL_sect)
NameError: global name 'utils' is not defined
```

**Comment by sachinmalepati** [comment]
issue resolved, review it

**Comment by krishh-konar** [comment]
Working fine now, closing the issue.
